/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc.java_poo_gabrielcassal;

/**
 *
 * @author gabrc
 */
public class Frm_About extends javax.swing.JFrame {

    /**
     * Creates new form Frm_About
     */
    public Frm_About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_Gera = new javax.swing.JPanel();
        L_Titl = new javax.swing.JLabel();
        P_Desc = new javax.swing.JPanel();
        L_Text1 = new javax.swing.JLabel();
        L_Text2 = new javax.swing.JLabel();
        L_Text3 = new javax.swing.JLabel();
        L_Text4 = new javax.swing.JLabel();
        L_Text5 = new javax.swing.JLabel();
        L_Text6 = new javax.swing.JLabel();
        B_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P_Gera.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        L_Titl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        L_Titl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Titl.setText("Projeto POO \"Cálculos\"");

        P_Desc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        L_Text1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        L_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Text1.setText("Projeto para primeira avaliação de POO do professor André Olímpio.");

        L_Text2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        L_Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Text2.setText("Feito por: Gabriel Coelho Cassal");

        L_Text3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        L_Text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Text3.setText("Github: github.com/gabrcass/");

        L_Text4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        L_Text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Text4.setText("Versão: 1.0.0");

        L_Text5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        L_Text5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Text5.setText("Set/2020");

        L_Text6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        L_Text6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Text6.setText("Desenvolvido no NetBeans IDE 8.2");

        javax.swing.GroupLayout P_DescLayout = new javax.swing.GroupLayout(P_Desc);
        P_Desc.setLayout(P_DescLayout);
        P_DescLayout.setHorizontalGroup(
            P_DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_DescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Text1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addComponent(L_Text2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_Text3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_Text4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_Text5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_Text6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        P_DescLayout.setVerticalGroup(
            P_DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_DescLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Text3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Text4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Text5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Text6)
                .addContainerGap())
        );

        B_Ok.setText("OK");
        B_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_GeraLayout = new javax.swing.GroupLayout(P_Gera);
        P_Gera.setLayout(P_GeraLayout);
        P_GeraLayout.setHorizontalGroup(
            P_GeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_GeraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_GeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_Titl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(P_GeraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_GeraLayout.setVerticalGroup(
            P_GeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_GeraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Titl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_Ok)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Gera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_Gera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_OkActionPerformed
        dispose();
    }//GEN-LAST:event_B_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Ok;
    private javax.swing.JLabel L_Text1;
    private javax.swing.JLabel L_Text2;
    private javax.swing.JLabel L_Text3;
    private javax.swing.JLabel L_Text4;
    private javax.swing.JLabel L_Text5;
    private javax.swing.JLabel L_Text6;
    private javax.swing.JLabel L_Titl;
    private javax.swing.JPanel P_Desc;
    private javax.swing.JPanel P_Gera;
    // End of variables declaration//GEN-END:variables
}
