/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc.java_poo_gabrielcassal;

import javafx.util.converter.DoubleStringConverter;

/**
 *
 * @author gabrc
 */
public class Frm_CalcMate extends javax.swing.JFrame {

    /**
     * Creates new form Frm_CalcMate
     */
    public Frm_CalcMate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_Tabu = new javax.swing.JPanel();
        L_TabuNum = new javax.swing.JLabel();
        Tf_TabuNum = new javax.swing.JTextField();
        B_TabuLimp = new javax.swing.JButton();
        B_TabuCalc = new javax.swing.JButton();
        List_TabuList = new java.awt.List();
        P_Grau = new javax.swing.JPanel();
        L_GrauNum = new javax.swing.JLabel();
        Tf_GrauNum = new javax.swing.JTextField();
        B_GrauCalc = new javax.swing.JButton();
        B_GrauLimp = new javax.swing.JButton();
        L_GrauSeno = new javax.swing.JLabel();
        L_GrauCossR = new javax.swing.JLabel();
        L_GrauCoss = new javax.swing.JLabel();
        L_GrauSenoR = new javax.swing.JLabel();
        P_Fato = new javax.swing.JPanel();
        L_FatoNum = new javax.swing.JLabel();
        Tf_FatoNum = new javax.swing.JTextField();
        B_FatoCalc = new javax.swing.JButton();
        B_FatoLimp = new javax.swing.JButton();
        L_FatoResu = new javax.swing.JLabel();
        L_FatoResuR = new javax.swing.JLabel();
        P_Mult = new javax.swing.JPanel();
        L_MultNum = new javax.swing.JLabel();
        Tf_MultNum = new javax.swing.JTextField();
        B_MultCalc = new javax.swing.JButton();
        B_MultLimp = new javax.swing.JButton();
        L_MultDobr = new javax.swing.JLabel();
        L_MultTripR = new javax.swing.JLabel();
        L_MultTrip = new javax.swing.JLabel();
        L_MultDobrR = new javax.swing.JLabel();
        L_MultQuin = new javax.swing.JLabel();
        L_MultQuinR = new javax.swing.JLabel();
        L_MultQuad = new javax.swing.JLabel();
        L_MultQuadR = new javax.swing.JLabel();
        P_Pote = new javax.swing.JPanel();
        L_PoteNum = new javax.swing.JLabel();
        Tf_PoteNum = new javax.swing.JTextField();
        B_PoteCalc = new javax.swing.JButton();
        B_PoteLimp = new javax.swing.JButton();
        L_PoteQuad = new javax.swing.JLabel();
        L_PoteCuboR = new javax.swing.JLabel();
        L_PoteCubo = new javax.swing.JLabel();
        L_PoteQuadR = new javax.swing.JLabel();
        L_PoteSext = new javax.swing.JLabel();
        L_PoteSextR = new javax.swing.JLabel();
        L_PoteQuin = new javax.swing.JLabel();
        L_PoteQuinR = new javax.swing.JLabel();
        L_PoteQuar = new javax.swing.JLabel();
        L_PoteQuarR = new javax.swing.JLabel();
        L_PoteRaiz = new javax.swing.JLabel();
        L_PoteRaizR = new javax.swing.JLabel();
        P_Medi = new javax.swing.JPanel();
        L_MediNum1 = new javax.swing.JLabel();
        Tf_MediNum1 = new javax.swing.JTextField();
        B_MediCalc = new javax.swing.JButton();
        B_MediLimp = new javax.swing.JButton();
        L_MediNum2 = new javax.swing.JLabel();
        Tf_MediNum2 = new javax.swing.JTextField();
        L_MediNum3 = new javax.swing.JLabel();
        Tf_MediNum3 = new javax.swing.JTextField();
        L_MediNum4 = new javax.swing.JLabel();
        Tf_MediNum4 = new javax.swing.JTextField();
        L_MediMedi = new javax.swing.JLabel();
        L_MediMediR = new javax.swing.JLabel();
        P_Todo = new javax.swing.JPanel();
        B_TodoFech = new javax.swing.JButton();
        B_TodoLimp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Cálculo Matemático"); // NOI18N

        P_Tabu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tabuada"));
        P_Tabu.setToolTipText("");
        P_Tabu.setName("Tabuada"); // NOI18N
        P_Tabu.setOpaque(false);

        L_TabuNum.setText("Número: ");

        Tf_TabuNum.setMinimumSize(new java.awt.Dimension(50, 25));
        Tf_TabuNum.setPreferredSize(new java.awt.Dimension(100, 25));

        B_TabuLimp.setText("Limpar");
        B_TabuLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_TabuLimp.setPreferredSize(new java.awt.Dimension(100, 35));
        B_TabuLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TabuLimpActionPerformed(evt);
            }
        });

        B_TabuCalc.setText("Calcular");
        B_TabuCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_TabuCalc.setPreferredSize(new java.awt.Dimension(100, 35));
        B_TabuCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TabuCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_TabuLayout = new javax.swing.GroupLayout(P_Tabu);
        P_Tabu.setLayout(P_TabuLayout);
        P_TabuLayout.setHorizontalGroup(
            P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TabuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P_TabuLayout.createSequentialGroup()
                        .addComponent(L_TabuNum)
                        .addGap(18, 18, 18)
                        .addComponent(Tf_TabuNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(List_TabuList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_TabuCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_TabuLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_TabuLayout.setVerticalGroup(
            P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TabuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_TabuCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_TabuNum)
                        .addComponent(Tf_TabuNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(P_TabuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_TabuLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(List_TabuList, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        P_Grau.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Graus:"));

        L_GrauNum.setText("Número: ");

        Tf_GrauNum.setMinimumSize(new java.awt.Dimension(50, 25));
        Tf_GrauNum.setPreferredSize(new java.awt.Dimension(100, 25));

        B_GrauCalc.setText("Calcular");
        B_GrauCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_GrauCalc.setPreferredSize(new java.awt.Dimension(100, 35));
        B_GrauCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GrauCalcActionPerformed(evt);
            }
        });

        B_GrauLimp.setText("Limpar");
        B_GrauLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_GrauLimp.setPreferredSize(new java.awt.Dimension(100, 35));
        B_GrauLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GrauLimpActionPerformed(evt);
            }
        });

        L_GrauSeno.setText("Seno: ");

        L_GrauCossR.setText("0");

        L_GrauCoss.setText("Cosseno: ");

        L_GrauSenoR.setText("0");

        javax.swing.GroupLayout P_GrauLayout = new javax.swing.GroupLayout(P_Grau);
        P_Grau.setLayout(P_GrauLayout);
        P_GrauLayout.setHorizontalGroup(
            P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_GrauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_GrauNum)
                    .addComponent(L_GrauCoss)
                    .addComponent(L_GrauSeno))
                .addGap(18, 18, 18)
                .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_GrauSenoR)
                    .addComponent(L_GrauCossR)
                    .addComponent(Tf_GrauNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_GrauCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_GrauLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        P_GrauLayout.setVerticalGroup(
            P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_GrauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_GrauCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_GrauNum)
                        .addComponent(Tf_GrauNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_GrauLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_GrauSeno)
                    .addComponent(L_GrauSenoR))
                .addGap(28, 28, 28)
                .addGroup(P_GrauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_GrauCossR)
                    .addComponent(L_GrauCoss))
                .addContainerGap())
        );

        P_Fato.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fatorial:"));

        L_FatoNum.setText("Número: ");

        Tf_FatoNum.setMinimumSize(new java.awt.Dimension(50, 25));
        Tf_FatoNum.setPreferredSize(new java.awt.Dimension(100, 25));

        B_FatoCalc.setText("Calcular");
        B_FatoCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_FatoCalc.setPreferredSize(new java.awt.Dimension(100, 35));
        B_FatoCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FatoCalcActionPerformed(evt);
            }
        });

        B_FatoLimp.setText("Limpar");
        B_FatoLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_FatoLimp.setPreferredSize(new java.awt.Dimension(100, 35));

        L_FatoResu.setText("Resultado: ");

        L_FatoResuR.setText("0");

        javax.swing.GroupLayout P_FatoLayout = new javax.swing.GroupLayout(P_Fato);
        P_Fato.setLayout(P_FatoLayout);
        P_FatoLayout.setHorizontalGroup(
            P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_FatoResu)
                    .addComponent(L_FatoNum))
                .addGap(18, 18, 18)
                .addGroup(P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tf_FatoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_FatoResuR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_FatoCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_FatoLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        P_FatoLayout.setVerticalGroup(
            P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_FatoCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_FatoNum)
                        .addComponent(Tf_FatoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(P_FatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_FatoLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_FatoResu)
                    .addComponent(L_FatoResuR))
                .addContainerGap())
        );

        P_Mult.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Múltiplos:"));

        L_MultNum.setText("Número: ");

        Tf_MultNum.setMinimumSize(new java.awt.Dimension(50, 25));
        Tf_MultNum.setPreferredSize(new java.awt.Dimension(100, 25));

        B_MultCalc.setText("Calcular");
        B_MultCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_MultCalc.setPreferredSize(new java.awt.Dimension(100, 35));
        B_MultCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MultCalcActionPerformed(evt);
            }
        });

        B_MultLimp.setText("Limpar");
        B_MultLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_MultLimp.setPreferredSize(new java.awt.Dimension(100, 35));
        B_MultLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MultLimpActionPerformed(evt);
            }
        });

        L_MultDobr.setText("Dobro: ");

        L_MultTripR.setText("0");

        L_MultTrip.setText("Triplo: ");

        L_MultDobrR.setText("0");

        L_MultQuin.setText("Quíntuplo: ");

        L_MultQuinR.setText("0");

        L_MultQuad.setText("Quádruplo: ");

        L_MultQuadR.setText("0");

        javax.swing.GroupLayout P_MultLayout = new javax.swing.GroupLayout(P_Mult);
        P_Mult.setLayout(P_MultLayout);
        P_MultLayout.setHorizontalGroup(
            P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_MultNum)
                    .addComponent(L_MultTrip)
                    .addComponent(L_MultDobr))
                .addGap(18, 18, 18)
                .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P_MultLayout.createSequentialGroup()
                        .addComponent(L_MultDobrR)
                        .addGap(18, 18, 18)
                        .addComponent(L_MultQuad)
                        .addGap(18, 18, 18)
                        .addComponent(L_MultQuadR))
                    .addComponent(Tf_MultNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_MultLayout.createSequentialGroup()
                        .addComponent(L_MultTripR)
                        .addGap(18, 18, 18)
                        .addComponent(L_MultQuin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_MultQuinR)))
                .addGap(18, 89, Short.MAX_VALUE)
                .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_MultCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_MultLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        P_MultLayout.setVerticalGroup(
            P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_MultCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_MultNum)
                        .addComponent(Tf_MultNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_MultLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_MultQuad)
                    .addComponent(L_MultQuadR)
                    .addComponent(L_MultDobrR)
                    .addComponent(L_MultDobr))
                .addGap(28, 28, 28)
                .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_MultQuinR)
                        .addComponent(L_MultQuin))
                    .addGroup(P_MultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_MultTripR)
                        .addComponent(L_MultTrip)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_Pote.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Potência:"));

        L_PoteNum.setText("Número: ");

        Tf_PoteNum.setMinimumSize(new java.awt.Dimension(50, 25));
        Tf_PoteNum.setPreferredSize(new java.awt.Dimension(100, 25));

        B_PoteCalc.setText("Calcular");
        B_PoteCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_PoteCalc.setPreferredSize(new java.awt.Dimension(100, 35));
        B_PoteCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PoteCalcActionPerformed(evt);
            }
        });

        B_PoteLimp.setText("Limpar");
        B_PoteLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_PoteLimp.setPreferredSize(new java.awt.Dimension(100, 35));
        B_PoteLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PoteLimpActionPerformed(evt);
            }
        });

        L_PoteQuad.setText("Quadrado");

        L_PoteCuboR.setText("0");
        L_PoteCuboR.setMaximumSize(new java.awt.Dimension(18, 14));

        L_PoteCubo.setText("Cubo: ");

        L_PoteQuadR.setText("0");
        L_PoteQuadR.setMaximumSize(new java.awt.Dimension(18, 14));

        L_PoteSext.setText("6ª Potência: ");

        L_PoteSextR.setText("0");
        L_PoteSextR.setMaximumSize(new java.awt.Dimension(18, 14));

        L_PoteQuin.setText("5ª Potência: ");

        L_PoteQuinR.setText("0");
        L_PoteQuinR.setMaximumSize(new java.awt.Dimension(18, 14));

        L_PoteQuar.setText("4ª Potência: ");

        L_PoteQuarR.setText("0");
        L_PoteQuarR.setMaximumSize(new java.awt.Dimension(18, 14));

        L_PoteRaiz.setText("Raiz Quadrada: ");

        L_PoteRaizR.setText("0");
        L_PoteRaizR.setMaximumSize(new java.awt.Dimension(18, 14));

        javax.swing.GroupLayout P_PoteLayout = new javax.swing.GroupLayout(P_Pote);
        P_Pote.setLayout(P_PoteLayout);
        P_PoteLayout.setHorizontalGroup(
            P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_PoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_PoteLayout.createSequentialGroup()
                        .addComponent(L_PoteNum)
                        .addGap(18, 18, 18)
                        .addComponent(Tf_PoteNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P_PoteLayout.createSequentialGroup()
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_PoteLayout.createSequentialGroup()
                                .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_PoteQuar)
                                    .addComponent(L_PoteCubo))
                                .addGap(18, 18, 18)
                                .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_PoteQuarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_PoteCuboR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_PoteQuadR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(L_PoteQuad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_PoteRaiz)
                            .addComponent(L_PoteSext)
                            .addComponent(L_PoteQuin))
                        .addGap(18, 18, 18)
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_PoteSextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PoteRaizR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PoteQuinR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_PoteCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_PoteLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        P_PoteLayout.setVerticalGroup(
            P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_PoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_PoteCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_PoteNum)
                        .addComponent(Tf_PoteNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_PoteLayout.createSequentialGroup()
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_PoteLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(L_PoteQuadR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_PoteQuad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_PoteCuboR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PoteCubo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_PoteQuarR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PoteQuar)))
                    .addGroup(P_PoteLayout.createSequentialGroup()
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_PoteQuin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_PoteQuinR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_PoteSextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PoteSext))
                        .addGap(18, 18, 18)
                        .addGroup(P_PoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_PoteRaizR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_PoteRaiz))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        P_Medi.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Média aritimética:"));

        L_MediNum1.setText("1º Valor: ");
        L_MediNum1.setAlignmentX(0.5F);
        L_MediNum1.setMaximumSize(new java.awt.Dimension(0, 0));
        L_MediNum1.setMinimumSize(new java.awt.Dimension(0, 0));

        Tf_MediNum1.setBorder(null);
        Tf_MediNum1.setMaximumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum1.setMinimumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum1.setPreferredSize(new java.awt.Dimension(100, 25));

        B_MediCalc.setText("Calcular");
        B_MediCalc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_MediCalc.setPreferredSize(new java.awt.Dimension(100, 35));
        B_MediCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MediCalcActionPerformed(evt);
            }
        });

        B_MediLimp.setText("Limpar");
        B_MediLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_MediLimp.setPreferredSize(new java.awt.Dimension(100, 35));
        B_MediLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MediLimpActionPerformed(evt);
            }
        });

        L_MediNum2.setText("2º Valor: ");
        L_MediNum2.setAlignmentX(0.5F);
        L_MediNum2.setMaximumSize(new java.awt.Dimension(0, 0));
        L_MediNum2.setMinimumSize(new java.awt.Dimension(0, 0));

        Tf_MediNum2.setBorder(null);
        Tf_MediNum2.setMaximumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum2.setMinimumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum2.setPreferredSize(new java.awt.Dimension(100, 25));

        L_MediNum3.setText("3º Valor:");
        L_MediNum3.setAlignmentX(0.5F);
        L_MediNum3.setMaximumSize(new java.awt.Dimension(0, 0));
        L_MediNum3.setMinimumSize(new java.awt.Dimension(0, 0));

        Tf_MediNum3.setBorder(null);
        Tf_MediNum3.setMaximumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum3.setMinimumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum3.setPreferredSize(new java.awt.Dimension(100, 25));

        L_MediNum4.setText("4º Valor:");
        L_MediNum4.setAlignmentX(0.5F);
        L_MediNum4.setMaximumSize(new java.awt.Dimension(0, 0));
        L_MediNum4.setMinimumSize(new java.awt.Dimension(0, 0));

        Tf_MediNum4.setBorder(null);
        Tf_MediNum4.setMaximumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum4.setMinimumSize(new java.awt.Dimension(0, 0));
        Tf_MediNum4.setPreferredSize(new java.awt.Dimension(100, 25));

        L_MediMedi.setText("Média: ");

        L_MediMediR.setText("0");

        javax.swing.GroupLayout P_MediLayout = new javax.swing.GroupLayout(P_Medi);
        P_Medi.setLayout(P_MediLayout);
        P_MediLayout.setHorizontalGroup(
            P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MediLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_MediLayout.createSequentialGroup()
                        .addComponent(L_MediNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tf_MediNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(B_MediCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P_MediLayout.createSequentialGroup()
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_MediNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_MediMedi))
                        .addGap(23, 23, 23)
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_MediMediR)
                            .addComponent(Tf_MediNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_MediLayout.createSequentialGroup()
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_MediNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_MediNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tf_MediNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_MediNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(B_MediLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        P_MediLayout.setVerticalGroup(
            P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MediLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_MediLayout.createSequentialGroup()
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_MediNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_MediNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_MediNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_MediNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_MediNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_MediNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_MediNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_MediNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_MediLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_MediMedi)
                            .addComponent(L_MediMediR))
                        .addContainerGap())
                    .addGroup(P_MediLayout.createSequentialGroup()
                        .addComponent(B_MediCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B_MediLimp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        P_Todo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        B_TodoFech.setText("Fechar Formulário");
        B_TodoFech.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_TodoFech.setPreferredSize(new java.awt.Dimension(100, 35));
        B_TodoFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TodoFechActionPerformed(evt);
            }
        });

        B_TodoLimp.setText("Limpar Todos");
        B_TodoLimp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_TodoLimp.setPreferredSize(new java.awt.Dimension(100, 35));
        B_TodoLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TodoLimpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_TodoLayout = new javax.swing.GroupLayout(P_Todo);
        P_Todo.setLayout(P_TodoLayout);
        P_TodoLayout.setHorizontalGroup(
            P_TodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_TodoLimp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_TodoFech, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_TodoLayout.setVerticalGroup(
            P_TodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_TodoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(P_TodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_TodoFech, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_TodoLimp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P_Tabu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_Grau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P_Mult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_Fato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_Pote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P_Todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_Medi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(P_Fato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(P_Mult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(P_Medi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(P_Todo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(P_Tabu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Grau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P_Pote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_Tabu.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_TodoFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TodoFechActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_B_TodoFechActionPerformed

    private void B_TabuCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TabuCalcActionPerformed
        int tabuadaR;
        int tabuada = Integer.parseInt(Tf_TabuNum.getText());
        for(int contador=1; contador<= 10; contador++){
            tabuadaR=tabuada*contador;
            List_TabuList.add(Integer.toString(tabuadaR));
        }
    }//GEN-LAST:event_B_TabuCalcActionPerformed

    private void B_TabuLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TabuLimpActionPerformed
        // set 0 in field Tf_TabuNum
        List_TabuList.removeAll();
        Tf_TabuNum.setText("");
        Tf_TabuNum.requestFocus();
    }//GEN-LAST:event_B_TabuLimpActionPerformed

    private void B_PoteCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PoteCalcActionPerformed
        // TODO add your handling code here:
        double base = Double.parseDouble(Tf_PoteNum.getText());
        double quadrado = Math.pow(base, 2);
        double cubo = Math.pow(base, 3);
        double quarta = Math.pow(base, 4);
        double quinta = Math.pow(base, 5);
        double sexta = Math.pow(base, 6);
        double raiz = Math.sqrt(base);
        L_PoteQuadR.setText(Double.toString(quadrado));
        L_PoteCuboR.setText(Double.toString(cubo));
        L_PoteQuarR.setText(Double.toString(quarta));
        L_PoteQuinR.setText(Double.toString(quinta));
        L_PoteSextR.setText(Double.toString(sexta));
        L_PoteRaizR.setText(Double.toString(raiz));
        
    }//GEN-LAST:event_B_PoteCalcActionPerformed

    private void B_PoteLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PoteLimpActionPerformed
        // TODO add your handling code here:
        L_PoteQuadR.setText("0");
        L_PoteCuboR.setText("0");
        L_PoteQuarR.setText("0");
        L_PoteQuinR.setText("0");
        L_PoteSextR.setText("0");
        L_PoteRaizR.setText("0");
        Tf_PoteNum.setText("0");
        Tf_PoteNum.requestFocus();
    }//GEN-LAST:event_B_PoteLimpActionPerformed

    private void B_MultCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MultCalcActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(Tf_MultNum.getText());
        double dobr = n1*2;
        double trip = n1*3;
        double quad = n1*4;
        double quin = n1*5;
        L_MultDobrR.setText(Double.toString(dobr));
        L_MultTripR.setText(Double.toString(trip));
        L_MultQuadR.setText(Double.toString(quad));
        L_MultQuinR.setText(Double.toString(quin));
        
    }//GEN-LAST:event_B_MultCalcActionPerformed

    private void B_MultLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MultLimpActionPerformed
        // TODO add your handling code here:
        L_MultDobrR.setText("0");
        L_MultTripR.setText("0");
        L_MultQuadR.setText("0");
        L_MultQuinR.setText("0");
        Tf_MultNum.requestFocus();
    }//GEN-LAST:event_B_MultLimpActionPerformed

    private void B_MediCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MediCalcActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(Tf_MediNum1.getText());
        double n2 = Double.parseDouble(Tf_MediNum2.getText());
        double n3 = Double.parseDouble(Tf_MediNum3.getText());
        double n4 = Double.parseDouble(Tf_MediNum4.getText());
        double nr=(n1+n2+n3+n4)/4;
        L_MediMediR.setText(Double.toString(nr));
    }//GEN-LAST:event_B_MediCalcActionPerformed

    private void B_MediLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MediLimpActionPerformed
        // TODO add your handling code here:
        Tf_MediNum1.setText("0");
        Tf_MediNum2.setText("0");
        Tf_MediNum3.setText("0");
        Tf_MediNum4.setText("0");
        L_MediMediR.setText("");
        Tf_MediNum1.requestFocus();
    }//GEN-LAST:event_B_MediLimpActionPerformed

    private void B_TodoLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TodoLimpActionPerformed
        // TODO add your handling code here:
        Tf_MediNum1.setText("0");
        Tf_MediNum2.setText("0");
        Tf_MediNum3.setText("0");
        Tf_MediNum4.setText("0");
        L_MediMediR.setText("0");
        L_MultDobrR.setText("0");
        L_MultTripR.setText("0");
        L_MultQuadR.setText("0");
        L_MultQuinR.setText("0");
        L_PoteQuadR.setText("0");
        L_PoteCuboR.setText("0");
        L_PoteQuarR.setText("0");
        L_PoteQuinR.setText("0");
        L_PoteSextR.setText("0");
        L_PoteRaizR.setText("0");
        Tf_PoteNum.setText("0");
        List_TabuList.removeAll();
        Tf_TabuNum.setText("0");
        Tf_GrauNum.setText("0");
        Tf_FatoNum.setText("0");
        L_FatoResuR.setText("0");
        L_GrauCossR.setText("0");
        L_GrauSenoR.setText("0");
    }//GEN-LAST:event_B_TodoLimpActionPerformed

    private void B_GrauCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GrauCalcActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(Tf_GrauNum.getText());
        double grau=valor*Math.PI/180;
        L_GrauCossR.setText(Double.toString(Math.cos(grau)));        
        L_GrauSenoR.setText(Double.toString(Math.sin(grau)));
    }//GEN-LAST:event_B_GrauCalcActionPerformed

    private void B_GrauLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GrauLimpActionPerformed
        // TODO add your handling code here:
        L_GrauSenoR.setText("0");
        L_GrauCossR.setText("0");
        Tf_GrauNum.setText("");
        Tf_GrauNum.requestFocus();
    }//GEN-LAST:event_B_GrauLimpActionPerformed

    private void B_FatoCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FatoCalcActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_B_FatoCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcMate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcMate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcMate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcMate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_CalcMate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_FatoCalc;
    private javax.swing.JButton B_FatoLimp;
    private javax.swing.JButton B_GrauCalc;
    private javax.swing.JButton B_GrauLimp;
    private javax.swing.JButton B_MediCalc;
    private javax.swing.JButton B_MediLimp;
    private javax.swing.JButton B_MultCalc;
    private javax.swing.JButton B_MultLimp;
    private javax.swing.JButton B_PoteCalc;
    private javax.swing.JButton B_PoteLimp;
    private javax.swing.JButton B_TabuCalc;
    private javax.swing.JButton B_TabuLimp;
    private javax.swing.JButton B_TodoFech;
    private javax.swing.JButton B_TodoLimp;
    private javax.swing.JLabel L_FatoNum;
    private javax.swing.JLabel L_FatoResu;
    private javax.swing.JLabel L_FatoResuR;
    private javax.swing.JLabel L_GrauCoss;
    private javax.swing.JLabel L_GrauCossR;
    private javax.swing.JLabel L_GrauNum;
    private javax.swing.JLabel L_GrauSeno;
    private javax.swing.JLabel L_GrauSenoR;
    private javax.swing.JLabel L_MediMedi;
    private javax.swing.JLabel L_MediMediR;
    private javax.swing.JLabel L_MediNum1;
    private javax.swing.JLabel L_MediNum2;
    private javax.swing.JLabel L_MediNum3;
    private javax.swing.JLabel L_MediNum4;
    private javax.swing.JLabel L_MultDobr;
    private javax.swing.JLabel L_MultDobrR;
    private javax.swing.JLabel L_MultNum;
    private javax.swing.JLabel L_MultQuad;
    private javax.swing.JLabel L_MultQuadR;
    private javax.swing.JLabel L_MultQuin;
    private javax.swing.JLabel L_MultQuinR;
    private javax.swing.JLabel L_MultTrip;
    private javax.swing.JLabel L_MultTripR;
    private javax.swing.JLabel L_PoteCubo;
    private javax.swing.JLabel L_PoteCuboR;
    private javax.swing.JLabel L_PoteNum;
    private javax.swing.JLabel L_PoteQuad;
    private javax.swing.JLabel L_PoteQuadR;
    private javax.swing.JLabel L_PoteQuar;
    private javax.swing.JLabel L_PoteQuarR;
    private javax.swing.JLabel L_PoteQuin;
    private javax.swing.JLabel L_PoteQuinR;
    private javax.swing.JLabel L_PoteRaiz;
    private javax.swing.JLabel L_PoteRaizR;
    private javax.swing.JLabel L_PoteSext;
    private javax.swing.JLabel L_PoteSextR;
    private javax.swing.JLabel L_TabuNum;
    private java.awt.List List_TabuList;
    private javax.swing.JPanel P_Fato;
    private javax.swing.JPanel P_Grau;
    private javax.swing.JPanel P_Medi;
    private javax.swing.JPanel P_Mult;
    private javax.swing.JPanel P_Pote;
    private javax.swing.JPanel P_Tabu;
    private javax.swing.JPanel P_Todo;
    private javax.swing.JTextField Tf_FatoNum;
    private javax.swing.JTextField Tf_GrauNum;
    private javax.swing.JTextField Tf_MediNum1;
    private javax.swing.JTextField Tf_MediNum2;
    private javax.swing.JTextField Tf_MediNum3;
    private javax.swing.JTextField Tf_MediNum4;
    private javax.swing.JTextField Tf_MultNum;
    private javax.swing.JTextField Tf_PoteNum;
    private javax.swing.JTextField Tf_TabuNum;
    // End of variables declaration//GEN-END:variables
}
