/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc.java_poo_gabrielcassal;

import java.util.Locale;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrc
 */
public class Frm_CalcFina extends javax.swing.JFrame {

    public void subtotal(){
        double V_total = 
                Double.parseDouble(Tf_ContQuanBe.getText())*69.90 + 
                Double.parseDouble(Tf_ContQuanBl.getText())*119.90 + 
                Double.parseDouble(Tf_ContQuanBo.getText())*6.90 + 
                Double.parseDouble(Tf_ContQuanCa.getText())*38.90 + 
                Double.parseDouble(Tf_ContQuanCh.getText())*14.90 + 
                Double.parseDouble(Tf_ContQuanCr.getText())*19.90 + 
                Double.parseDouble(Tf_ContQuanCs.getText())*59.90 + 
                Double.parseDouble(Tf_ContQuanL.getText())*24.90 + 
                Double.parseDouble(Tf_ContQuanM.getText())*9.90 + 
                Double.parseDouble(Tf_ContQuanP.getText())*39.90 + 
                Double.parseDouble(Tf_ContQuanS.getText())*99.90;
        
        L_SubR.setText(Double.toString(V_total));
    }
    /**
     * Creates new form Frm_CalcFina
     */
    public Frm_CalcFina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gb_Form = new javax.swing.ButtonGroup();
        P_Cont = new javax.swing.JPanel();
        L_ContProd = new javax.swing.JLabel();
        Cb_ContCr = new javax.swing.JCheckBox();
        L_ContPrec = new javax.swing.JLabel();
        L_ContQuan = new javax.swing.JLabel();
        L_ContValo = new javax.swing.JLabel();
        L_ContPrecCr = new javax.swing.JLabel();
        Tf_ContQuanCr = new javax.swing.JTextField();
        L_ContValoCr = new javax.swing.JLabel();
        Cb_ContCs = new javax.swing.JCheckBox();
        L_ContPrecCs = new javax.swing.JLabel();
        L_ContValoCs = new javax.swing.JLabel();
        Tf_ContQuanCs = new javax.swing.JTextField();
        Tf_ContQuanBl = new javax.swing.JTextField();
        L_ContValoBo = new javax.swing.JLabel();
        Cb_ContBl = new javax.swing.JCheckBox();
        L_ContPrecBl = new javax.swing.JLabel();
        L_ContPrecP = new javax.swing.JLabel();
        Cb_ContP = new javax.swing.JCheckBox();
        L_ContValoBl = new javax.swing.JLabel();
        Tf_ContQuanP = new javax.swing.JTextField();
        Cb_ContS = new javax.swing.JCheckBox();
        Tf_ContQuanS = new javax.swing.JTextField();
        L_ContPrecS = new javax.swing.JLabel();
        L_ContValoP = new javax.swing.JLabel();
        Cb_ContCa = new javax.swing.JCheckBox();
        L_ContPrecCa = new javax.swing.JLabel();
        L_ContValoS = new javax.swing.JLabel();
        Cb_ContM = new javax.swing.JCheckBox();
        L_ContPrecM = new javax.swing.JLabel();
        L_ContValoCa = new javax.swing.JLabel();
        Cb_ContL = new javax.swing.JCheckBox();
        L_ContPrecL = new javax.swing.JLabel();
        L_ContValoM = new javax.swing.JLabel();
        Cb_ContBe = new javax.swing.JCheckBox();
        L_ContPrecBe = new javax.swing.JLabel();
        L_ContValoJ = new javax.swing.JLabel();
        Cb_ContCh = new javax.swing.JCheckBox();
        L_ContPrecCh = new javax.swing.JLabel();
        L_ContValoBe = new javax.swing.JLabel();
        Tf_ContQuanCa = new javax.swing.JTextField();
        Tf_ContQuanM = new javax.swing.JTextField();
        Tf_ContQuanL = new javax.swing.JTextField();
        Tf_ContQuanBe = new javax.swing.JTextField();
        Tf_ContQuanCh = new javax.swing.JTextField();
        Cb_ContBo = new javax.swing.JCheckBox();
        L_ContPrecBo = new javax.swing.JLabel();
        Tf_ContQuanBo = new javax.swing.JTextField();
        L_ContValoCh = new javax.swing.JLabel();
        Cb_ContJ = new javax.swing.JCheckBox();
        L_ContPrecJ = new javax.swing.JLabel();
        Tf_ContQuanJ = new javax.swing.JTextField();
        L_ContValoL = new javax.swing.JLabel();
        B_Sub = new javax.swing.JButton();
        L_Sub = new javax.swing.JLabel();
        L_SubR = new javax.swing.JLabel();
        P_Form = new javax.swing.JPanel();
        Rb_FormVist = new javax.swing.JRadioButton();
        Rb_FormPraz = new javax.swing.JRadioButton();
        L_FormQuan = new javax.swing.JLabel();
        Cb_FormQuan = new javax.swing.JComboBox<>();
        L_FormValo = new javax.swing.JLabel();
        L_FormValoR = new javax.swing.JLabel();
        L_Desc = new javax.swing.JLabel();
        L_DescR = new javax.swing.JLabel();
        L_Paga = new javax.swing.JLabel();
        L_PagaR = new javax.swing.JLabel();
        B_Calc = new javax.swing.JButton();
        B_Limp = new javax.swing.JButton();
        B_Fech = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Cálculo Financeiro"); // NOI18N

        P_Cont.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Controle de Vendas:"));

        L_ContProd.setText("Produto:");

        Cb_ContCr.setText("Camisa Regata");
        Cb_ContCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContCrActionPerformed(evt);
            }
        });

        L_ContPrec.setText("Preço (em R$):");

        L_ContQuan.setText("Quantidade:");

        L_ContValo.setText("Valor (em R$):");

        L_ContPrecCr.setText("19.90");

        Tf_ContQuanCr.setEditable(false);
        Tf_ContQuanCr.setText("0");
        Tf_ContQuanCr.setPreferredSize(new java.awt.Dimension(50, 20));

        L_ContValoCr.setText("0.00");

        Cb_ContCs.setText("Camisa Social");
        Cb_ContCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContCsActionPerformed(evt);
            }
        });

        L_ContPrecCs.setText("59.90");

        L_ContValoCs.setText("0.00");

        Tf_ContQuanCs.setEditable(false);
        Tf_ContQuanCs.setText("0");
        Tf_ContQuanCs.setPreferredSize(new java.awt.Dimension(50, 20));
        Tf_ContQuanCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_ContQuanCsActionPerformed(evt);
            }
        });

        Tf_ContQuanBl.setEditable(false);
        Tf_ContQuanBl.setText("0");
        Tf_ContQuanBl.setPreferredSize(new java.awt.Dimension(50, 20));

        L_ContValoBo.setText("0.00");

        Cb_ContBl.setText("Blusa");
        Cb_ContBl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContBlActionPerformed(evt);
            }
        });

        L_ContPrecBl.setText("119.90");

        L_ContPrecP.setText("39.90");

        Cb_ContP.setText("Pullover");
        Cb_ContP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContPActionPerformed(evt);
            }
        });

        L_ContValoBl.setText("0.00");

        Tf_ContQuanP.setEditable(false);
        Tf_ContQuanP.setText("0");
        Tf_ContQuanP.setPreferredSize(new java.awt.Dimension(50, 20));

        Cb_ContS.setText("Sapato");
        Cb_ContS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContSActionPerformed(evt);
            }
        });

        Tf_ContQuanS.setEditable(false);
        Tf_ContQuanS.setText("0");
        Tf_ContQuanS.setPreferredSize(new java.awt.Dimension(50, 20));

        L_ContPrecS.setText("99.90");

        L_ContValoP.setText("0.00");

        Cb_ContCa.setText("Calça");
        Cb_ContCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContCaActionPerformed(evt);
            }
        });

        L_ContPrecCa.setText("38.90");

        L_ContValoS.setText("0.00");

        Cb_ContM.setText("Meias");
        Cb_ContM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContMActionPerformed(evt);
            }
        });

        L_ContPrecM.setText("9.90");

        L_ContValoCa.setText("0.00");

        Cb_ContL.setText("Luvas");
        Cb_ContL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContLActionPerformed(evt);
            }
        });

        L_ContPrecL.setText("24.90");

        L_ContValoM.setText("0.00");

        Cb_ContBe.setText("Bermuda");
        Cb_ContBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContBeActionPerformed(evt);
            }
        });

        L_ContPrecBe.setText("69.90");

        L_ContValoJ.setText("0.00");

        Cb_ContCh.setText("Chinelo");
        Cb_ContCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContChActionPerformed(evt);
            }
        });

        L_ContPrecCh.setText("14.90");

        L_ContValoBe.setText("0.00");

        Tf_ContQuanCa.setEditable(false);
        Tf_ContQuanCa.setText("0");
        Tf_ContQuanCa.setPreferredSize(new java.awt.Dimension(50, 20));

        Tf_ContQuanM.setEditable(false);
        Tf_ContQuanM.setText("0");
        Tf_ContQuanM.setPreferredSize(new java.awt.Dimension(50, 20));

        Tf_ContQuanL.setEditable(false);
        Tf_ContQuanL.setText("0");
        Tf_ContQuanL.setPreferredSize(new java.awt.Dimension(50, 20));

        Tf_ContQuanBe.setEditable(false);
        Tf_ContQuanBe.setText("0");
        Tf_ContQuanBe.setPreferredSize(new java.awt.Dimension(50, 20));

        Tf_ContQuanCh.setEditable(false);
        Tf_ContQuanCh.setText("0");
        Tf_ContQuanCh.setPreferredSize(new java.awt.Dimension(50, 20));

        Cb_ContBo.setText("Boné");
        Cb_ContBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContBoActionPerformed(evt);
            }
        });

        L_ContPrecBo.setText("6.90");

        Tf_ContQuanBo.setEditable(false);
        Tf_ContQuanBo.setText("0");
        Tf_ContQuanBo.setPreferredSize(new java.awt.Dimension(50, 20));

        L_ContValoCh.setText("0.00");

        Cb_ContJ.setText("Jaqueta");
        Cb_ContJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_ContJActionPerformed(evt);
            }
        });

        L_ContPrecJ.setText("329.90");

        Tf_ContQuanJ.setEditable(false);
        Tf_ContQuanJ.setText("0");
        Tf_ContQuanJ.setPreferredSize(new java.awt.Dimension(50, 20));

        L_ContValoL.setText("0.00");

        javax.swing.GroupLayout P_ContLayout = new javax.swing.GroupLayout(P_Cont);
        P_Cont.setLayout(P_ContLayout);
        P_ContLayout.setHorizontalGroup(
            P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_ContLayout.createSequentialGroup()
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ContLayout.createSequentialGroup()
                        .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_ContLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(L_ContProd))
                            .addGroup(P_ContLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Cb_ContCr))
                            .addGroup(P_ContLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Cb_ContBe))
                            .addGroup(P_ContLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Cb_ContBo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_ContPrec)
                            .addGroup(P_ContLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_ContPrecCs)
                                    .addComponent(L_ContPrecCr)
                                    .addComponent(L_ContPrecBl)
                                    .addComponent(L_ContPrecP)
                                    .addComponent(L_ContPrecS)
                                    .addComponent(L_ContPrecCa)
                                    .addComponent(L_ContPrecM)
                                    .addComponent(L_ContPrecL)
                                    .addComponent(L_ContPrecJ)
                                    .addComponent(L_ContPrecBe)
                                    .addComponent(L_ContPrecCh)
                                    .addComponent(L_ContPrecBo))))
                        .addGap(60, 60, 60))
                    .addGroup(P_ContLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cb_ContS)
                            .addComponent(Cb_ContBl)
                            .addComponent(Cb_ContP)
                            .addComponent(Cb_ContCa)
                            .addComponent(Cb_ContM)
                            .addComponent(Cb_ContL)
                            .addComponent(Cb_ContCh)
                            .addComponent(Cb_ContJ)
                            .addComponent(Cb_ContCs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tf_ContQuanBl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_ContLayout.createSequentialGroup()
                        .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_ContQuan)
                            .addComponent(Tf_ContQuanCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_ContQuanCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tf_ContQuanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_ContValo)
                            .addGroup(P_ContLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_ContValoCs)
                                    .addComponent(L_ContValoCr)
                                    .addComponent(L_ContValoBl)
                                    .addComponent(L_ContValoP)
                                    .addComponent(L_ContValoS)
                                    .addComponent(L_ContValoCa)
                                    .addComponent(L_ContValoM)
                                    .addComponent(L_ContValoL)
                                    .addComponent(L_ContValoJ)
                                    .addComponent(L_ContValoBe)
                                    .addComponent(L_ContValoCh)
                                    .addComponent(L_ContValoBo)))))
                    .addComponent(Tf_ContQuanS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_ContQuanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        P_ContLayout.setVerticalGroup(
            P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ContLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_ContPrec, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_ContProd)
                        .addComponent(L_ContQuan)
                        .addComponent(L_ContValo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContCr)
                    .addComponent(L_ContPrecCr)
                    .addComponent(Tf_ContQuanCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoCr))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContCs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContValoCs)
                    .addComponent(L_ContPrecCs)
                    .addComponent(Tf_ContQuanCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContBl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(L_ContPrecBl)
                    .addComponent(Tf_ContQuanBl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoBl))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContPrecP)
                    .addComponent(Tf_ContQuanP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoP))
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContS, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(L_ContPrecS)
                    .addComponent(Tf_ContQuanS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoS))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContPrecCa)
                    .addComponent(Tf_ContQuanCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoCa))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContPrecM)
                    .addComponent(Tf_ContQuanM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoM))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContPrecL)
                    .addComponent(Tf_ContQuanL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoL))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContPrecJ)
                    .addComponent(Tf_ContQuanJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoJ))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContBe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_ContPrecBe)
                    .addComponent(Tf_ContQuanBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoBe))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_ContCh, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(L_ContPrecCh)
                    .addComponent(Tf_ContQuanCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoCh))
                .addGap(0, 0, 0)
                .addGroup(P_ContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_ContQuanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ContValoBo)
                    .addComponent(L_ContPrecBo)
                    .addComponent(Cb_ContBo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        B_Sub.setFont(B_Sub.getFont().deriveFont(B_Sub.getFont().getStyle() | java.awt.Font.BOLD, B_Sub.getFont().getSize()+5));
        B_Sub.setText("Sub-Total");
        B_Sub.setPreferredSize(new java.awt.Dimension(150, 50));
        B_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SubActionPerformed(evt);
            }
        });

        L_Sub.setFont(L_Sub.getFont().deriveFont(L_Sub.getFont().getSize()+5f));
        L_Sub.setText("Sub-Total: R$ ");

        L_SubR.setFont(L_SubR.getFont().deriveFont(L_SubR.getFont().getStyle() | java.awt.Font.BOLD, L_SubR.getFont().getSize()+5));
        L_SubR.setText("0.00");

        P_Form.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Forma de Pagamento: "));

        Gb_Form.add(Rb_FormVist);
        Rb_FormVist.setText("À Vista");
        Rb_FormVist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_FormVistActionPerformed(evt);
            }
        });

        Gb_Form.add(Rb_FormPraz);
        Rb_FormPraz.setText("À Prazo");
        Rb_FormPraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb_FormPrazActionPerformed(evt);
            }
        });

        L_FormQuan.setText("Quantidade de Parcelas:");
        L_FormQuan.setPreferredSize(new java.awt.Dimension(200, 14));

        Cb_FormQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        Cb_FormQuan.setEnabled(false);

        L_FormValo.setText("Valor da Parcelas: R$");

        L_FormValoR.setText("0.00");

        javax.swing.GroupLayout P_FormLayout = new javax.swing.GroupLayout(P_Form);
        P_Form.setLayout(P_FormLayout);
        P_FormLayout.setHorizontalGroup(
            P_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rb_FormVist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rb_FormPraz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_FormQuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(P_FormLayout.createSequentialGroup()
                        .addComponent(L_FormValo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L_FormValoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cb_FormQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        P_FormLayout.setVerticalGroup(
            P_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Rb_FormVist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Rb_FormPraz)
                .addGap(18, 18, 18)
                .addGroup(P_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_FormQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cb_FormQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(P_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_FormValo)
                    .addComponent(L_FormValoR))
                .addContainerGap())
        );

        L_Desc.setText("Total de Descontos: R$");

        L_DescR.setText("0.00");

        L_Paga.setText("Total a Pagar: R$ ");

        L_PagaR.setText("0.00");

        B_Calc.setText("Calcular Total");
        B_Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CalcActionPerformed(evt);
            }
        });

        B_Limp.setText("Limpar Todos");
        B_Limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LimpActionPerformed(evt);
            }
        });

        B_Fech.setText("Fechar formulário");
        B_Fech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(P_Cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_Paga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L_PagaR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_Desc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(L_DescR, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(B_Fech))
                            .addComponent(P_Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_Calc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B_Limp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(B_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L_SubR, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(P_Cont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(P_Form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_Desc)
                            .addComponent(L_DescR))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_Paga)
                            .addComponent(L_PagaR))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_Calc)
                            .addComponent(B_Limp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_Fech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_SubR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cb_ContLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContLActionPerformed
        // TODO add your handling code here:
        if (Cb_ContL.isSelected() == true ){
            Tf_ContQuanL.setEditable(true);
        }
        if (Cb_ContL.isSelected() == false ){
            Tf_ContQuanL.setEditable(false);
            Tf_ContQuanL.setText("0");
        }
    }//GEN-LAST:event_Cb_ContLActionPerformed

    private void Tf_ContQuanCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_ContQuanCsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_ContQuanCsActionPerformed

    private void B_FechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FechActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certeza ?", "Alerta",JOptionPane.YES_NO_OPTION);
        if (confirma == 0){
            dispose();
        }
    }//GEN-LAST:event_B_FechActionPerformed

    private void Cb_ContCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContCrActionPerformed
        // TODO add your handling code here:
        if (Cb_ContCr.isSelected() == true){
            Tf_ContQuanCr.setEnabled(true);
            Tf_ContQuanCr.setText("");
            Tf_ContQuanCr.requestFocus();
        }
        if (Cb_ContCr.isSelected() == false){
            Tf_ContQuanCr.setEnabled(false);
            Tf_ContQuanCr.setText("0");
        }
    }//GEN-LAST:event_Cb_ContCrActionPerformed

    private void Cb_ContCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContCsActionPerformed
        if (Cb_ContCs.isSelected() == true){
            Tf_ContQuanCs.setEnabled(true);
            Tf_ContQuanCs.setText("");
            Tf_ContQuanCs.requestFocus();
        }
        if (Cb_ContCs.isSelected() == false){
            Tf_ContQuanCs.setEnabled(false);
            Tf_ContQuanCs.setText("0");
        }
    }//GEN-LAST:event_Cb_ContCsActionPerformed

    private void Cb_ContBlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContBlActionPerformed
        // TODO add your handling code here:
        if (Cb_ContBl.isSelected() == true ){
            Tf_ContQuanBl.setEditable(true);
        }
        if (Cb_ContBl.isSelected() == false ){
            Tf_ContQuanBl.setEditable(false);
            Tf_ContQuanBl.setText("0");
        }
    }//GEN-LAST:event_Cb_ContBlActionPerformed

    private void Cb_ContPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContPActionPerformed
        // TODO add your handling code here:
        if (Cb_ContP.isSelected() == true ){
            Tf_ContQuanP.setEditable(true);
        }
        if (Cb_ContP.isSelected() == false ){
            Tf_ContQuanP.setEditable(false);
            Tf_ContQuanP.setText("0");
        }
    }//GEN-LAST:event_Cb_ContPActionPerformed

    private void Cb_ContSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContSActionPerformed
        // TODO add your handling code here:
        if (Cb_ContS.isSelected() == true ){
            Tf_ContQuanS.setEditable(true);
        }
        if (Cb_ContS.isSelected() == false ){
            Tf_ContQuanS.setEditable(false);
            Tf_ContQuanS.setText("0");
        }
    }//GEN-LAST:event_Cb_ContSActionPerformed

    private void Cb_ContCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContCaActionPerformed
        // TODO add your handling code here:
        if (Cb_ContCa.isSelected() == true ){
            Tf_ContQuanCa.setEditable(true);
        }
        if (Cb_ContCa.isSelected() == false ){
            Tf_ContQuanCa.setEditable(false);
            Tf_ContQuanCa.setText("0");
        }
    }//GEN-LAST:event_Cb_ContCaActionPerformed

    private void Cb_ContMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContMActionPerformed
        // TODO add your handling code here:
        if (Cb_ContM.isSelected() == true ){
            Tf_ContQuanM.setEditable(true);
        }
        if (Cb_ContM.isSelected() == false ){
            Tf_ContQuanM.setEditable(false);
            Tf_ContQuanM.setText("0");
        }
    }//GEN-LAST:event_Cb_ContMActionPerformed

    private void Cb_ContJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContJActionPerformed
        // TODO add your handling code here:
        if (Cb_ContJ.isSelected() == true ){
            Tf_ContQuanJ.setEditable(true);
        }
        if (Cb_ContJ.isSelected() == false ){
            Tf_ContQuanJ.setEditable(false);
            Tf_ContQuanJ.setText("0");
        }
    }//GEN-LAST:event_Cb_ContJActionPerformed

    private void Cb_ContBeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContBeActionPerformed
        // TODO add your handling code here:
        if (Cb_ContBe.isSelected() == true ){
            Tf_ContQuanBe.setEditable(true);
        }
        if (Cb_ContBe.isSelected() == false ){
            Tf_ContQuanBe.setEditable(false);
            Tf_ContQuanBe.setText("0");
        }
    }//GEN-LAST:event_Cb_ContBeActionPerformed

    private void Cb_ContChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContChActionPerformed
        // TODO add your handling code here:
        if (Cb_ContCh.isSelected() == true ){
            Tf_ContQuanCh.setEditable(true);
        }
        if (Cb_ContCh.isSelected() == false ){
            Tf_ContQuanCh.setEditable(false);
            Tf_ContQuanCh.setText("0");
        }
    }//GEN-LAST:event_Cb_ContChActionPerformed

    private void Cb_ContBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_ContBoActionPerformed
        // TODO add your handling code here:
        if (Cb_ContBo.isSelected() == true ){
            Tf_ContQuanBo.setEditable(true);
        }
        if (Cb_ContBo.isSelected() == false ){
            Tf_ContQuanBo.setEditable(false);
            Tf_ContQuanBo.setText("0");
        }
    }//GEN-LAST:event_Cb_ContBoActionPerformed

    private void B_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SubActionPerformed
        subtotal();
    }//GEN-LAST:event_B_SubActionPerformed

    private void B_CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CalcActionPerformed
        // TODO add your handling code here:
        String Combobox = (String) Cb_FormQuan.getSelectedItem();
        subtotal();
        if (Rb_FormVist.isSelected() == true){
            Cb_FormQuan.setEnabled(false);
            double desc = subtotal*0.115;
            double total = subtotal-desc;
            L_PagaR.setText(Double.toString(total));
            L_DescR.setText(Double.toString(desc));
            L_FormValoR.setText("0.00");
        }
        if (Rb_FormPraz.isSelected() == true) {
            Cb_FormQuan.setEnabled(true);
            double total = (subtotal) + (Double.parseDouble(Combobox)*6.90);
            double pagar = total + (total*0.01);
            L_PagaR.setText(Double.toString(pagar));
            L_DescR.setText("0.00");
            double parcela = total / Double.parseDouble(Combobox);

            L_FormValoR.setText(Double.toString(parcela));
        }

    }//GEN-LAST:event_B_CalcActionPerformed

    private void Rb_FormVistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_FormVistActionPerformed
        // TODO add your handling code here:
        Cb_FormQuan.setEnabled(false);
    }//GEN-LAST:event_Rb_FormVistActionPerformed

    private void Rb_FormPrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb_FormPrazActionPerformed
        // TODO add your handling code here:
        Cb_FormQuan.setEnabled(true);
    }//GEN-LAST:event_Rb_FormPrazActionPerformed

    private void B_LimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LimpActionPerformed
        // TODO add your handling code here:
        Tf_ContQuanBe.setText("0");
        Tf_ContQuanBl.setText("0");
        Tf_ContQuanBo.setText("0");
        Tf_ContQuanCa.setText("0");
        Tf_ContQuanCh.setText("0");
        Tf_ContQuanCr.setText("0");
        Tf_ContQuanCs.setText("0");
        Tf_ContQuanJ.setText("0");
        Tf_ContQuanL.setText("0");
        Tf_ContQuanM.setText("0");
        Tf_ContQuanP.setText("0");
        Tf_ContQuanS.setText("0");
        L_ContValoBl.setText("0");
        L_ContValoBe.setText("0");
        L_ContValoBo.setText("0");
        L_ContValoCa.setText("0");
        L_ContValoCh.setText("0");
        L_ContValoCr.setText("0");
        L_ContValoCs.setText("0");
        L_ContValoJ.setText("0");
        L_ContValoL.setText("0");
        L_ContValoM.setText("0");
        L_ContValoP.setText("0");
        L_ContValoS.setText("0");
        Cb_ContBo.setSelected(false);
        Cb_ContBe.setSelected(false);
        Cb_ContBl.setSelected(false);
        Cb_ContCa.setSelected(false);
        Cb_ContCh.setSelected(false);
        Cb_ContCr.setSelected(false);
        Cb_ContCs.setSelected(false);
        Cb_ContJ.setSelected(false);
        Cb_ContL.setSelected(false);
        Cb_ContM.setSelected(false);
        Cb_ContP.setSelected(false);
        Cb_ContS.setSelected(false);
        Tf_ContQuanBe.setEditable(false);
        Tf_ContQuanBl.setEditable(false);
        Tf_ContQuanBo.setEditable(false);
        Tf_ContQuanCa.setEditable(false);
        Tf_ContQuanCh.setEditable(false);
        Tf_ContQuanCr.setEditable(false);
        Tf_ContQuanCs.setEditable(false);
        Tf_ContQuanJ.setEditable(false);
        Tf_ContQuanL.setEditable(false);
        Tf_ContQuanM.setEditable(false);
        Tf_ContQuanP.setEditable(false);
        Tf_ContQuanS.setEditable(false);
        L_SubR.setText("0.00");
        
        
        
    }//GEN-LAST:event_B_LimpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcFina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcFina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcFina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_CalcFina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_CalcFina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Calc;
    private javax.swing.JButton B_Fech;
    private javax.swing.JButton B_Limp;
    private javax.swing.JButton B_Sub;
    private javax.swing.JCheckBox Cb_ContBe;
    private javax.swing.JCheckBox Cb_ContBl;
    private javax.swing.JCheckBox Cb_ContBo;
    private javax.swing.JCheckBox Cb_ContCa;
    private javax.swing.JCheckBox Cb_ContCh;
    private javax.swing.JCheckBox Cb_ContCr;
    private javax.swing.JCheckBox Cb_ContCs;
    private javax.swing.JCheckBox Cb_ContJ;
    private javax.swing.JCheckBox Cb_ContL;
    private javax.swing.JCheckBox Cb_ContM;
    private javax.swing.JCheckBox Cb_ContP;
    private javax.swing.JCheckBox Cb_ContS;
    private javax.swing.JComboBox<String> Cb_FormQuan;
    private javax.swing.ButtonGroup Gb_Form;
    private javax.swing.JLabel L_ContPrec;
    private javax.swing.JLabel L_ContPrecBe;
    private javax.swing.JLabel L_ContPrecBl;
    private javax.swing.JLabel L_ContPrecBo;
    private javax.swing.JLabel L_ContPrecCa;
    private javax.swing.JLabel L_ContPrecCh;
    private javax.swing.JLabel L_ContPrecCr;
    private javax.swing.JLabel L_ContPrecCs;
    private javax.swing.JLabel L_ContPrecJ;
    private javax.swing.JLabel L_ContPrecL;
    private javax.swing.JLabel L_ContPrecM;
    private javax.swing.JLabel L_ContPrecP;
    private javax.swing.JLabel L_ContPrecS;
    private javax.swing.JLabel L_ContProd;
    private javax.swing.JLabel L_ContQuan;
    private javax.swing.JLabel L_ContValo;
    private javax.swing.JLabel L_ContValoBe;
    private javax.swing.JLabel L_ContValoBl;
    private javax.swing.JLabel L_ContValoBo;
    private javax.swing.JLabel L_ContValoCa;
    private javax.swing.JLabel L_ContValoCh;
    private javax.swing.JLabel L_ContValoCr;
    private javax.swing.JLabel L_ContValoCs;
    private javax.swing.JLabel L_ContValoJ;
    private javax.swing.JLabel L_ContValoL;
    private javax.swing.JLabel L_ContValoM;
    private javax.swing.JLabel L_ContValoP;
    private javax.swing.JLabel L_ContValoS;
    private javax.swing.JLabel L_Desc;
    private javax.swing.JLabel L_DescR;
    private javax.swing.JLabel L_FormQuan;
    private javax.swing.JLabel L_FormValo;
    private javax.swing.JLabel L_FormValoR;
    private javax.swing.JLabel L_Paga;
    private javax.swing.JLabel L_PagaR;
    private javax.swing.JLabel L_Sub;
    private javax.swing.JLabel L_SubR;
    private javax.swing.JPanel P_Cont;
    private javax.swing.JPanel P_Form;
    private javax.swing.JRadioButton Rb_FormPraz;
    private javax.swing.JRadioButton Rb_FormVist;
    private javax.swing.JTextField Tf_ContQuanBe;
    private javax.swing.JTextField Tf_ContQuanBl;
    private javax.swing.JTextField Tf_ContQuanBo;
    private javax.swing.JTextField Tf_ContQuanCa;
    private javax.swing.JTextField Tf_ContQuanCh;
    private javax.swing.JTextField Tf_ContQuanCr;
    private javax.swing.JTextField Tf_ContQuanCs;
    private javax.swing.JTextField Tf_ContQuanJ;
    private javax.swing.JTextField Tf_ContQuanL;
    private javax.swing.JTextField Tf_ContQuanM;
    private javax.swing.JTextField Tf_ContQuanP;
    private javax.swing.JTextField Tf_ContQuanS;
    // End of variables declaration//GEN-END:variables
}
